# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: cfapi12
  pool: 5
  username: 'hai12'
  password: 'sn1892000'
  host: localhost
  port: 5432


test:
  adapter: postgresql
  encoding: unicode
  database: cfapi12_test
  pool: 5
  username: 'hai12'
  password: 'sn1892000'

production:
  adapter: postgresql
  encoding: unicode
  database: cfapi12_test
  pool: 5
  username: 'hai12'
  password: 'sn1892000'